server:
  port: 8082
spring:
  application:
    name: pro-springboot-validation
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        watch:
          enabled: false
management:
  endpoints:
    web:
      exposure:
        include:
          - health
