server:
  port: 8082
spring:
  application:
    name: pro-springboot-validation
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/validation?useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        watch:
          enabled: false
seata:
  tx-service-group: default
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group: SEATA_GROUP
      application: seata-server
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group: SEATA_GROUP
      data-id: seata-client.properties
management:
  endpoints:
    web:
      exposure:
        include:
          - health
