server:
  port: 8081
spring:
  application:
    name: pro-springboot-comment
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/comment?useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false
        watch:
          enabled: false
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:9000
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
  client:
    undo:
      log-table: seata_undo
#feign:
#  sentinel:
#    enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
